name: ebalfred_common_sense
display_name: "EB-Alfred Common Sense Split"
description: "Common sense evaluation split testing implicit knowledge"
simulator: "ai2thor:v2_1_0"
task_class: "easi.tasks.ebalfred.task.EBAlfredTask"
action_space: []
max_steps: 50
dataset:
  source: huggingface
  repo_id: "oscarqjh/EB-Alfred_easi"
  subset: null
  split: "common_sense"
  zip_files:
    - "tasks.zip"
simulator_configs:
  quality: "MediumCloseFitShadows"
  screen_height: 500
  screen_width: 500
  additional_deps:
    - "gym"
    - "networkx"
    - "opencv-python"
agent:
  prompt_builder: "easi.tasks.ebalfred.prompts.EBAlfredPromptBuilder"
  prompt_builder_kwargs:
    n_shot: 10
    split: "base"
    use_feedback: true
