display_name: "EB-Navigation"
description: "EB-Navigation benchmark (object-goal navigation)"
simulator: "ai2thor:v5_0_0"
task_class: "easi.tasks.ebnavigation.task.EBNavigationTask"
max_steps: 20
dataset:
  source: huggingface
  repo_id: "oscarqjh/EB-Navigation_easi"
  subset: null
simulator_configs:
  render_platform: auto
  screen_height: 500
  screen_width: 500
  fov: 100
  success_threshold: 1.0
  grid_size: 0.1
  visibility_distance: 10.0
  boundingbox: false
agent:
  prompt_builder: "easi.tasks.ebnavigation.prompts.EBNavigationPromptBuilder"
  prompt_builder_kwargs:
    n_shot: 3
    use_feedback: true
    chat_history: true
    message_window_len: 5
  generation_kwargs:
    temperature: 0
    max_tokens: 2048
    top_k: 50
    top_p: 0.95
    do_sample: false
